site/djangobook/urls.py
from django.conf.urls.defaults import *
from djangobook.feeds import PublishedChaptersFeed, CommentFeed
from djangobook.views import *

urlpatterns = patterns('',
    (r'^admin/', include('django.contrib.admin.urls')),
    (r'^accounts/login/$',  'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    (    
        r'^feed/(?P<url>.*)/$', 
        'django.contrib.syndication.views.feed', 
        {'feed_dict': {"comments" : CommentFeed}}
    ),
    (
        r'^tools/removecomment/(?P<comment_id>\d+)/$',
        remove_comment,
    ),
    (
        r'^tools/markreviewed/(?P<comment_id>\d+)/$',
        mark_comment_reviewed,
    ),
    
    (
        r'^errata/$',
        errata,
    ),
    (
        r'^errata/submit/$',
        submit_erratum,
    ),
    
    (
        r'^contact/', 
        include('contact_form.urls'),
    ),
    
    # (
    #     r'^private/(?P<slug>[\w-]+)/$',
    #     private_toc
    # ),
    # (
    #     r'^private/(?P<slug>[\w-]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/$', 
    #     private_chapter
    # ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/$',
        toc
    ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/$', 
        chapter
    ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/comments/(?:(?P<nodenum>\d+)/)?$', 
        comments,
    ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/comments/counts/$', 
        comment_counts,
    ),
    (
        r'^feed/$', 
        'django.contrib.syndication.views.feed', 
        {'feed_dict': {"chapters" : PublishedChaptersFeed}, "url" : "chapters"}
    ),
)

site/djangobook/models.py
import pysvn
import datetime
import urlparse
from django.db import models
from django.utils import text
from django.core import validators
from unipath import Path

LANGUAGE_CHOICES = (
    ("en", "English"),
)

CHAPTER_TYPE_CHOICES = (
    ("C", "chapter"),
    ("A", "appendix"),
)

def isValidSVNRoot(field_data, all_data):
    c = pysvn.Client()
    try:
        c.info2(field_data, recurse=False)
    except pysvn.ClientError:
        raise validators.ValidationError("Please enter a valid SVN URL.")

class BookVersion(models.Model):
    version  = models.CharField(max_length=6)
    language = models.CharField(max_length=5, choices=LANGUAGE_CHOICES)
    svn_root = models.CharField(max_length=200, validator_list=[isValidSVNRoot])
    newer_version = models.ForeignKey('self', blank=True, null=True)
    
    class Admin:
        ordering = ("language", "version")
        list_display = ("version", "language")
        
    def __unicode__(self):
        return u"%s (%s)" % (self.version, self.get_language_display().lower())
        
    @models.permalink
    def permalink(self):
        return ("djangobook.views.toc", (self.language, self.version))

class Chapter(models.Model):
    type          = models.CharField(max_length=1, choices=CHAPTER_TYPE_CHOICES)
    number        = models.PositiveSmallIntegerField()
    title         = models.CharField(max_length=200)
    version       = models.ForeignKey(BookVersion, related_name="chapters")
    release_date  = models.DateTimeField(blank=True, null=True)
    comments_open = models.BooleanField("comments are open", default=True)
    code          = models.FileField(upload_to="code", blank=True, null=True)

    class Meta:
        unique_together = [("type", "number", "version")]
        ordering = ("version", "-type", "number")

    class Admin:
        list_filter = ("version",)
        list_display = ("title", "get_number_display", "version", "release_date", "comments_open")
        ordering = ("number",)

    def __unicode__(self):
        return u"%s %s: %s" % (self.get_type_display().title(), self.get_number_display(), self.title)
    
    def get_number_display(self):
        if self.type == "C":
            return str(self.number)
        else:
            return chr(ord('A') + self.number - 1)
    get_number_display.short_description = "Number"
    get_number_display.admin_order_field = "number"
            
    def get_number_url_fragment(self):
        if self.type == "C":
            return "%02i" % self.number
        else:
            return chr(ord('A') + self.number - 1)
    
    @models.permalink
    def permalink(self):
        return ("djangobook.views.chapter", (self.version.language, 
                                             self.version.version, 
                                             self.type,
                                             self.get_number_url_fragment()))

    def get_svn_url(self):
        filename = "%s%s.txt" % (self.get_type_display().lower(), self.get_number_url_fragment())
        return str(Path(self.version.svn_root).child(filename))
        
    def get_content(self):
        c = pysvn.Client()
        try:
            return c.cat(self.get_svn_url())
        except pysvn.ClientError:
            return None
        
    def is_released(self):
        return self.release_date and self.release_date < datetime.datetime.now()

    def get_public_comments(self):
        return self.comments.filter(is_removed=False).order_by("date_posted")
        
    def get_next_chapter(self):
        if not hasattr(self, "_next_chapter"):
            self._next_chapter = None
            toc = list(Chapter.objects.filter(version=self.version))
            index = toc.index(self)
            for c in toc[index+1:]:
                if c.is_released():
                    self._next_chapter = c
                    break;
        return self._next_chapter
        
    def get_previous_chapter(self):
        if not hasattr(self, "_prev_chapter"):
            self._prev_chapter = None
            toc = list(Chapter.objects.filter(version=self.version))
            index = toc.index(self)
            for c in reversed(toc[:index]):
                if c.is_released():
                    self._prev_chapter = c
                    break;
        return self._prev_chapter
        
    next = property(get_next_chapter)
    previous = property(get_previous_chapter)
    
class Comment(models.Model):
    chapter     = models.ForeignKey(Chapter, related_name="comments")
    name        = models.CharField(max_length=50)
    email       = models.EmailField()
    url         = models.URLField(verify_exists=False, blank=True)
    nodenum     = models.PositiveSmallIntegerField()
    comment     = models.TextField()
    date_posted = models.DateTimeField()
    is_removed  = models.BooleanField()
    is_reviewed = models.BooleanField()
        
    class Meta:
        ordering = ("-date_posted",)    
        
    class Admin:
        list_display = ("get_truncated_comment", "name", "email", "date_posted", "is_removed", "is_reviewed")
        list_filter = ("is_removed", "is_reviewed")
        search_fields = ("name", "email", "comment")
    
    def get_truncated_comment(self):
        return text.truncate_words(self.comment, 100)
    get_truncated_comment.short_description = "Comment"
    
class PrivateVersion(models.Model):
    slug = models.SlugField()
    svn_root = models.CharField(max_length=200, validator_list=[isValidSVNRoot])

    class Admin:
        list_display = ["slug", "svn_root"]

    def __unicode__(self):
        return u"Private version from %s" % self.svn_root

    @models.permalink
    def permalink(self):
        return ("djangobook.views.private_toc", (self.slug))

    def get_content(self, chapterslug):
        c = pysvn.Client()
        try:
            return c.cat(urlparse.urljoin(self.svn_root, chapterslug + ".txt"))
        except pysvn.ClientError:
            return None

class PrintVersion(models.Model):
    version = models.ForeignKey(BookVersion, related_name="print_versions")
    pub_date = models.DateField()
    isbn10 = models.CharField(max_length=10, verbose_name="ISBN (10)")
    print_title = models.CharField(max_length=150)
    
    class Meta:
        get_latest_by = "pub_date"
    
    class Admin:
        list_display = ["print_title", "version", "pub_date"]
        
    def __unicode__(self):
        return self.print_title
        
class Erratum(models.Model):
    book = models.ForeignKey(PrintVersion, related_name="errata")
    chapter = models.ForeignKey(Chapter, related_name="errata")
    page = models.PositiveSmallIntegerField()
    location = models.CharField(max_length=200, blank=True)
    description = models.TextField()
    reporter = models.CharField(max_length=200, blank=True)
    reporter_email = models.EmailField(blank=True)
    date = models.DateField()
    approved = models.BooleanField(default=False)
    link = models.URLField(blank=True)
    
    class Meta:
        verbose_name_plural = "errata"
    
    class Admin:
        list_display = ["chapter", "page", "location", "description", "reporter", "approved"]
        list_filter = ["book", "approved"]
        search_fields = ["page", "location", "description"]        

site/templates/errata/list.html
{% extends "base.html" %}

{% block title %}Errata{% endblock %}

{% block content %}
  {% if submitted %}
    <div class="message">Your error report has been submitted for review; thanks!</div>
  {% endif %}

  <h2 id="chapter-title">Errata <span>(<a href="submit/">report</a>)</span></h2>
  
  <div id="chapter-body">
    {% for e in erratum_list %}
      <div class="errata{% if forloop.last %} last{% endif %}" id="e{{ e.id }}">
        <h4>{{ e.chapter.get_type_display|title }} {{ e.chapter.get_number_display }}, page {{ e.page }}, {{ e.location }}:</h4>
        <p>{{ e.description }}</p>
        {% if e.reporter %}<p class="reported-by">Reported by {{ e.reporter }} on {{ e.date|date:"F j, Y" }}.</p>{% endif %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

site/templates/errata/submit.html
{% extends "base.html" %}

{% block title %}Report errata{% endblock %}

{% block content %}
  <h2 id="chapter-title">Report errata</h2>
  <div id="chapter-body">
    <form action="." method="post" accept-charset="utf-8">
      
      <p>
        <label for="id_reporter">Your name:</label>
        {% if form.reporter.errors %}<p class="errors">{{ form.reporter.errors.as_text }}</p>{% endif %}
        {{ form.reporter }}
      </p>
      
      <p>
        <label for="id_reporter_email">Your email address:</label>
        {% if form.reporter_email.errors %}<p class="errors">{{ form.reporter_email.errors.as_text }}</p>{% endif %}
        {{ form.reporter_email }}
      </p>

      <p>
        <label for="id_chapter">Chapter:</label>
        {% if form.chapter.errors %}<p class="errors">{{ form.chapter.errors.as_text }}</p>{% endif %}
        {{ form.chapter }}
      </p>
      
      <p>
        <label for="id_page">Page number:</label>
        {% if form.page.errors %}<p class="errors">{{ form.page.errors.as_text }}</p>{% endif %}
        {{ form.page }}
      </p>
      
      <p>
        <label for="id_location">Location: <span>(i.e. "third paragraph"; "first code snippet", etc.)</span></label>
        {% if form.location.errors %}<p class="errors">{{ form.location.errors.as_text }}</p>{% endif %}
        {{ form.location }}
      </p>

      <p>
        <label for="id_description">Description:</label>
        {% if form.description.errors %}<p class="errors">{{ form.description.errors.as_text }}</p>{% endif %}
        {{ form.description }}
      </p>
      
      <p class="submit"><input type="submit" value="Send &rarr;"></p>
    </form>
  </div>
{% endblock %}