site/djangobook/urls.py
from django.conf.urls.defaults import *
from djangobook.feeds import PublishedChaptersFeed, CommentFeed
from djangobook.views import *

urlpatterns = patterns('',
    (r'^admin/', include('django.contrib.admin.urls')),
    (r'^accounts/login/$',  'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    (    
        r'^feed/(?P<url>.*)/$', 
        'django.contrib.syndication.views.feed', 
        {'feed_dict': {"comments" : CommentFeed}}
    ),
    (
        r'^tools/removecomment/(?P<comment_id>\d+)/$',
        remove_comment,
    ),
    (
        r'^tools/markreviewed/(?P<comment_id>\d+)/$',
        mark_comment_reviewed,
    ),
    
    (
        r'^errata/$',
        errata,
    ),
    (
        r'^errata/submit/$',
        submit_erratum,
    ),
    
    (
        r'^contact/', 
        include('contact_form.urls'),
    ),
    
    # (
    #     r'^private/(?P<slug>[\w-]+)/$',
    #     private_toc
    # ),
    # (
    #     r'^private/(?P<slug>[\w-]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/$', 
    #     private_chapter
    # ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/$',
        toc
    ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/$', 
        chapter
    ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/comments/(?:(?P<nodenum>\d+)/)?$', 
        comments,
    ),
    (
        r'^(?P<lang>[\w-]+)/(?P<version>[\w\-\.]+)/(?P<type>chapter|appendix)(?P<chapter>\d{2}|[A-Z])/comments/counts/$', 
        comment_counts,
    ),
    (
        r'^feed/$', 
        'django.contrib.syndication.views.feed', 
        {'feed_dict': {"chapters" : PublishedChaptersFeed}, "url" : "chapters"}
    ),
)

site/djangobook/models.py
import pysvn
import datetime
import urlparse
from django.db import models
from django.utils import text
from django.core import validators
from unipath import Path

LANGUAGE_CHOICES = (
    ("en", "English"),
)

CHAPTER_TYPE_CHOICES = (
    ("C", "chapter"),
    ("A", "appendix"),
)

def isValidSVNRoot(field_data, all_data):
    c = pysvn.Client()
    try:
        c.info2(field_data, recurse=False)
    except pysvn.ClientError:
        raise validators.ValidationError("Please enter a valid SVN URL.")

class BookVersion(models.Model):
    version  = models.CharField(max_length=6)
    language = models.CharField(max_length=5, choices=LANGUAGE_CHOICES)
    svn_root = models.CharField(max_length=200, validator_list=[isValidSVNRoot])
    newer_version = models.ForeignKey('self', blank=True, null=True)
    
    class Admin:
        ordering = ("language", "version")
        list_display = ("version", "language")
        
    def __unicode__(self):
        return u"%s (%s)" % (self.version, self.get_language_display().lower())
        
    @models.permalink
    def permalink(self):
        return ("djangobook.views.toc", (self.language, self.version))

class Chapter(models.Model):
    type          = models.CharField(max_length=1, choices=CHAPTER_TYPE_CHOICES)
    number        = models.PositiveSmallIntegerField()
    title         = models.CharField(max_length=200)
    version       = models.ForeignKey(BookVersion, related_name="chapters")
    release_date  = models.DateTimeField(blank=True, null=True)
    comments_open = models.BooleanField("comments are open", default=True)
    code          = models.FileField(upload_to="code", blank=True, null=True)

    class Meta:
        unique_together = [("type", "number", "version")]
        ordering = ("version", "-type", "number")

    class Admin:
        list_filter = ("version",)
        list_display = ("title", "get_number_display", "version", "release_date", "comments_open")
        ordering = ("number",)

    def __unicode__(self):
        return u"%s %s: %s" % (self.get_type_display().title(), self.get_number_display(), self.title)
    
    def get_number_display(self):
        if self.type == "C":
            return str(self.number)
        else:
            return chr(ord('A') + self.number - 1)
    get_number_display.short_description = "Number"
    get_number_display.admin_order_field = "number"
            
    def get_number_url_fragment(self):
        if self.type == "C":
            return "%02i" % self.number
        else:
            return chr(ord('A') + self.number - 1)
    
    @models.permalink
    def permalink(self):
        return ("djangobook.views.chapter", (self.version.language, 
                                             self.version.version, 
                                             self.type,
                                             self.get_number_url_fragment()))

    def get_svn_url(self):
        filename = "%s%s.txt" % (self.get_type_display().lower(), self.get_number_url_fragment())
        return str(Path(self.version.svn_root).child(filename))
        
    def get_content(self):
        c = pysvn.Client()
        try:
            return c.cat(self.get_svn_url())
        except pysvn.ClientError:
            return None
        
    def is_released(self):
        return self.release_date and self.release_date < datetime.datetime.now()

    def get_public_comments(self):
        return self.comments.filter(is_removed=False).order_by("date_posted")
        
    def get_next_chapter(self):
        if not hasattr(self, "_next_chapter"):
            self._next_chapter = None
            toc = list(Chapter.objects.filter(version=self.version))
            index = toc.index(self)
            for c in toc[index+1:]:
                if c.is_released():
                    self._next_chapter = c
                    break;
        return self._next_chapter
        
    def get_previous_chapter(self):
        if not hasattr(self, "_prev_chapter"):
            self._prev_chapter = None
            toc = list(Chapter.objects.filter(version=self.version))
            index = toc.index(self)
            for c in reversed(toc[:index]):
                if c.is_released():
                    self._prev_chapter = c
                    break;
        return self._prev_chapter
        
    next = property(get_next_chapter)
    previous = property(get_previous_chapter)
    
class Comment(models.Model):
    chapter     = models.ForeignKey(Chapter, related_name="comments")
    name        = models.CharField(max_length=50)
    email       = models.EmailField()
    url         = models.URLField(verify_exists=False, blank=True)
    nodenum     = models.PositiveSmallIntegerField()
    comment     = models.TextField()
    date_posted = models.DateTimeField()
    is_removed  = models.BooleanField()
    is_reviewed = models.BooleanField()
        
    class Meta:
        ordering = ("-date_posted",)    
        
    class Admin:
        list_display = ("get_truncated_comment", "name", "email", "date_posted", "is_removed", "is_reviewed")
        list_filter = ("is_removed", "is_reviewed")
        search_fields = ("name", "email", "comment")
    
    def get_truncated_comment(self):
        return text.truncate_words(self.comment, 100)
    get_truncated_comment.short_description = "Comment"
    
class PrivateVersion(models.Model):
    slug = models.SlugField()
    svn_root = models.CharField(max_length=200, validator_list=[isValidSVNRoot])

    class Admin:
        list_display = ["slug", "svn_root"]

    def __unicode__(self):
        return u"Private version from %s" % self.svn_root

    @models.permalink
    def permalink(self):
        return ("djangobook.views.private_toc", (self.slug))

    def get_content(self, chapterslug):
        c = pysvn.Client()
        try:
            return c.cat(urlparse.urljoin(self.svn_root, chapterslug + ".txt"))
        except pysvn.ClientError:
            return None

class PrintVersion(models.Model):
    version = models.ForeignKey(BookVersion, related_name="print_versions")
    pub_date = models.DateField()
    isbn10 = models.CharField(max_length=10, verbose_name="ISBN (10)")
    print_title = models.CharField(max_length=150)
    
    class Meta:
        get_latest_by = "pub_date"
    
    class Admin:
        list_display = ["print_title", "version", "pub_date"]
        
    def __unicode__(self):
        return self.print_title
        
class Erratum(models.Model):
    book = models.ForeignKey(PrintVersion, related_name="errata")
    chapter = models.ForeignKey(Chapter, related_name="errata")
    page = models.PositiveSmallIntegerField()
    location = models.CharField(max_length=200, blank=True)
    description = models.TextField()
    reporter = models.CharField(max_length=200, blank=True)
    reporter_email = models.EmailField(blank=True)
    date = models.DateField()
    approved = models.BooleanField(default=False)
    link = models.URLField(blank=True)
    
    class Meta:
        verbose_name_plural = "errata"
    
    class Admin:
        list_display = ["chapter", "page", "location", "description", "reporter", "approved"]
        list_filter = ["book", "approved"]
        search_fields = ["page", "location", "description"]        

site/templates/book/chapter.html
{% extends "base.html" %}

{% block extrahead %}
  <link href="http://new-media.djangobook.com/yui/container/assets/container.css" type="text/css" media="screen" rel="stylesheet">
  <link href="http://new-media.djangobook.com/yui-ext/css/tabs.css" type="text/css" media="screen" rel="stylesheet">
  <link href="http://new-media.djangobook.com/yui-ext/css/resizable.css" type="text/css" media="screen" rel="stylesheet">
{% endblock %}

{% block title %}{{ release }}{% endblock %}

{% block hdnav %}{% include "book/nav.html" %}{% endblock %}
{% block ftnav %}{% include "book/nav.html" %}{% endblock %}

{% block content %}
  {% load markup %}
  {% if release.version.newer_version %}
    <div class="newer-version">
      You're reading an outdated version of this book; a 
      <a href="{{ release.version.newer_version.permalink }}">newer version</a>
      is available.
    </div>
  {% endif %}
  <h2 id="chapter-title">{{ content.title|safe }}</h2>
  {% if content.subtitle %}
    <h3 id="chapter-subtitle">{{ content.subtitle|safe }}</h3>
  {% endif %}
  <div id="chapter-body">
    {{ content.body|safe }}
  </div>
{% endblock %}

{% block afterbody %}
  <div id="highlight-floater"></div>
  <!-- comment dialog -->
  <div id="comments" class="yresizable-pinned">
    <div class="hd" id="comments-head">
      Comments <span class="close" onclick="Comments.close();">X</span>
    </div>
    <div class="bd">
      <div id="comment-tabs">
        
        <!-- comment form -->
        <div id="comment-tabs-form" class="tab">
          {% if release.comments_open %}
          <form action="comments/" method="post" id="commentform">
            <p>
              <input type="hidden" name="nodenum" value="">
              <label for="id_name">Name (required)</label>
              <input type="text" name="name" id="id_name" value="" tabindex="1">
            </p>
            <p>
              <label for="id_email">E-mail (required; will not be displayed)</label>
              <input type="text" name="email" id="id_email" value="" tabindex="2">
            </p>
            <p>
              <label for="id_url">Website</label>
              <input type="text" name="url" id="id_url" value="" tabindex="3">
            </p>
            <p>
              <label for="id_comment">Comment</label>
              <textarea name="comment" id="id_comment" tabindex="4" cols="40" rows="15"></textarea>
            </p>
          </form>
          {% else %}
            <h4>Comments are closed on this chapter.</h4>
            <p>
              We're no longer accepting comments on this version of this
              chapter.
            </p>
            <p>
              Many thanks to all those who commented.
            </p>
          {% endif %}
        </div>
        
        <!-- comments on this node tab: filled in dynamically -->
        <div id="comment-tabs-current" class="tab">
          <ol id="current-comments-list"></ol>
        </div>
        
        <!-- all comments tab: also dynamic -->
        <div id="comment-tabs-all" class="tab">
          <ol id="all-comments-list"></ol>
        </div>
        
        <!-- help -->
        <div id="comment-tabs-help" class="tab">
          <h4>About this comment system</h4>
          <p>
            This site is using a contextual comment system to help us gather
            targeted feedback about the book.  Instead of commenting on an
            entire chapter, you can leave comments on any indivdual "block"
            in the chapter. A "block" with comments looks like this:
          </p>
          <p class="image">
            <img src="http://media.djangobook.com/help/comments1.png" width="350" height="100">
          </p>
          <p>
            A "block" is a paragraph, list item, code sample, or other small
            chunk of content.  It'll get highlighted when you select it:
          </p>
          <p class="image">
            <img src="http://media.djangobook.com/help/comments2.png" width="350" height="100">
          </p>
          <p>
            To post a comment on a block, just click in the gutter next to the
            bit you want to comment on:
          </p>
          <p class="image">
            <img src="http://media.djangobook.com/help/comments3.png" width="350" height="100">
          </p>
          <p>
            As we edit the book, we'll review everyone's comments and roll them into
            a future version of the book. We'll mark reviewed comments with a little
            checkmark:
          </p>
          <p>
            Please make sure to leave a full name (and not a nickname or
            screenname) if you'd like your contributions acknowledged in print.
          </p>
          <p class="image">
            <img src="http://media.djangobook.com/help/comments4.png" width="350" height="100">
          </p>
          <p>
            Many, many thanks to <a href="http://www.jackslocum.com/yui/">Jack Slocum</a>;
            the inspiration and much of the code for the comment system comes from Jack's
            blog, and this site couldn't have been built without his wonderful 
            <code>YAHOO.ext</code> library.  Thanks also to Yahoo for YUI itself.
          </p>
        </div>

      </div>
    </div>
    <div class="ft">
       <div id="comments-message"></div>
       <div id="comments-submit-wrapper">
        <input type="button" id="comment-submit" value="Post comment" onclick="Comments.submitComment();">
        <input type="button" id="comment-close" value="Close" onclick="Comments.close();">
      </div>
    </div>
  </div>
  {% if user.is_authenticated %}
    <script type="text/javascript" src="http://new-media.djangobook.com/yui/yahoo/yahoo.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/yui/dom/dom.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/yui/event/event.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/yui/dragdrop/dragdrop.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/yui/connection/connection.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/yui-ext/yui-ext-core.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/yui-ext/tabs-lib.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/yui-ext/resizable-lib.js"></script>
    <script type="text/javascript" src="http://new-media.djangobook.com/djangobook.js"></script>
  {% else %}
    <script type="text/javascript" src="http://new-media.djangobook.com/djangobook-min-all.js"></script>
  {% endif %}
{% endblock %}

site/templates/book/comments_snippet.html
{% spaceless %}
	{% load markup %}
	{% if comments %}
		{% for c in comments %}
			<li class="comment" id="c{{ c.id }}">
				<dl>
					<dt>
						{% if c.url %}<a href="{{ c.url|escape }}" rel="nofollow">{% endif %}
						{{ c.name|escape }}
						{% if c.url %}</a>{% endif %}
						<span class="meta">{{ c.date_posted|date:"M jS, Y P" }}</span>
						{% if c.is_reviewed %}
							<span title="This comment has been reviewed and will be taken into account in a future version of the book. Thanks for contributing!" class="thanks">
								&radic;
							</span>
						{% endif %}
						{% if perms.djangobook %}
							<span class="actions">
								[<a href="/tools/removecomment/{{ c.id }}/" onclick="Comments.removeComment(this); return false;">&times;</a>]
								[<a href="/tools/markreviewed/{{ c.id }}/" onclick="Comments.markCommentHandled(this); return false;">&radic;</a>]
							</span>
						{% endif %}
					</dt>
					<dd>{{ c.comment|striptags|urlize|markdown }}</dd>
				</dl>
			</li>
		{% endfor %}
	{% else %}
		<li>No comments on this node.</li>
	{% endif %}
{% endspaceless %}

site/templates/book/nav.html
<div class="nav">
	{% if release.previous %}
		<a href='../{{ release.previous.get_type_display }}{{ release.previous.get_number_url_fragment }}/'>&laquo; previous</a> &loz;
	{% endif %}
	<a href="..">table of contents</a>
	{% if release.next %}
		&loz; <a href='../{{ release.next.get_type_display }}{{ release.next.get_number_url_fragment }}/'>next &raquo;</a>
	{% endif %}
</div>

site/templates/book/private_chapter.html
{% extends "book/chapter.html" %}

{% block extrahead %}
{% endblock %}

{% block title %}{{ content.title }}{% endblock %}

{% block content %}
	{% load markup %}
  <h2 id="chapter-title">{{ content.title }}</h2>
  <h3 id="chapter-subtitle">{{ version }}</h3>
  {% if content.subtitle %}
    <h3 id="chapter-subtitle">{{ content.subtitle }}</h3>
  {% endif %}
  <div id="chapter-body">
    {{ content.body }}
  </div>
{% endblock %}

{% block afterbody %}
{% endblock %}

site/templates/book/private_toc.html
{% extends "book/toc.html" %}

{% block content %}
  <h2 id="chapter-title">Table of contents</h2>
  <h2 id="chapter-subtitle">{{ version }}</h2>
  <ol class="toc">    
    {% for chapter in contents %}
      <li class="{% cycle a,b %}">
        {% if chapter.exists_in_branch %}
          <a href='{{ chapter.get_type_display }}{{ chapter.number|stringformat:"02i" }}/'>
            {{ chapter }}
          </a>  
        {% else %}
          {{ chapter }}
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

site/templates/book/toc.html
{% extends "base.html" %}

{% block content %}
  {% if book_version.newer_version %}
    <div class="newer-version">
      You're reading an outdated version of this book; a 
      <a href="{{ book_version.newer_version.permalink }}">newer version</a>
      is available.
    </div>
  {% endif %}
  <h2 id="chapter-title">Table of contents</h2>
  <h2 id="chapter-subtitle">{{ book_version.version|title }}, {{ book_version.get_language_display|title }}</h2>
  <ol class="toc">    
    {% for chapter in contents %}
      <li class="{% cycle a,b %}">
        <span class="release-date">
          {% if chapter.release_date %}
            {{ chapter.release_date|date:"F j, Y" }}
          {% else %}
            TBA
          {% endif %}
        </span>
        {% if chapter.is_released %}
          <a href='{{ chapter.get_type_display }}{{ chapter.get_number_url_fragment }}/'>
            {{ chapter }}
          </a>
        {% else %}
          {{ chapter }}
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}